force-app/main/default/objects/Retail_Territory__c/Retail_Territory__c.object-meta.xml
<CustomObject>
    <description>This is the main object for Zip code territory tracking</description>
    <label>Retail Territory</label>
    <nameField>
        <label>Retail Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Territory__c/fields/Assignments__c.field-meta.xml
<CustomField>
    <fullName>Assignments__c</fullName>
    <label>Assignments</label>
    <summaryForeignKey>Territory_Assignment__c.Retail_Territory__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Retail_Territory__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <externalId>true</externalId>
    <label>Zip Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Territory_Assignment__c/Territory_Assignment__c.object-meta.xml
<CustomObject>
    <description>This is the main object to be able to assign the territory to a user.</description>
    <label>Territory Assignment</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Territory Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Assignment__c/fields/Retail_Territory__c.field-meta.xml
<CustomField>
    <fullName>Retail_Territory__c</fullName>
    <label>Retail Territory</label>
    <referenceTo>Retail_Territory__c</referenceTo>
    <relationshipLabel>Territory Assignments</relationshipLabel>
    <relationshipName>Territory_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Territory_Assignment__c/fields/User_Assigned__c.field-meta.xml
<CustomField>
    <fullName>User_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Assigned</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Assignment__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <formula>Retail_Territory__r.Zip_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/selectors/Credomatic_RetailTerritoriesSelector.cls
public class Credomatic_RetailTerritoriesSelector extends fflib_SObjectSelector
implements Credomatic_IRetailTerritoriesSelector
{
    public static Credomatic_IRetailTerritoriesSelector newInstance() {
        return (Credomatic_IRetailTerritoriesSelector) Credomatic_Application.selector.newInstance(Retail_Territory__c.SObjectType);
    }
    
    //To be reviewed the required fields on the queries
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Retail_Territory__c.Id,
            Retail_Territory__c.Name,
            Retail_Territory__c.OwnerId,
            Retail_Territory__c.Zip_Code__c,
            Retail_Territory__c.Assignments__c
             };
    }
    
    public Schema.SObjectType getSObjectType() {
        return Retail_Territory__c.sObjectType;
    }
    
    public List<Retail_Territory__c> selectById(Set<ID> idSet) {
        return (List<Retail_Territory__c>) selectSObjectsById(idSet);
    }
    
    public List<Retail_Territory__c> selectByZip(Set<String> zipCodes) {
      	fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Zip_Code__c IN :zipCodes');
        query.subselectQuery('Territory_Assignments__r')
            .selectField('User_Assigned__c')
            .selectField('Zip_Code__c');
        
        return (List<Retail_Territory__c>) Database.query( query.toSOQL() );
    }
    
}