force-app/main/default/objects/Retail_Territory__c/Retail_Territory__c.object-meta.xml
<CustomObject>
    <description>This is the main object for Zip code territory tracking</description>
    <label>Retail Territory</label>
    <nameField>
        <label>Retail Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Territory__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <externalId>true</externalId>
    <label>Zip Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Territory_Assignment__c/Territory_Assignment__c.object-meta.xml
<CustomObject>
    <description>This is the main object to be able to assign the territory to a user.</description>
    <label>Territory Assignment</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Territory Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Assignment__c/fields/Retail_Territory__c.field-meta.xml
<CustomField>
    <fullName>Retail_Territory__c</fullName>
    <label>Retail Territory</label>
    <referenceTo>Retail_Territory__c</referenceTo>
    <relationshipLabel>Territory Assignments</relationshipLabel>
    <relationshipName>Territory_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Territory_Assignment__c/fields/User_Assigned__c.field-meta.xml
<CustomField>
    <fullName>User_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Assigned</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Assignment__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <formula>Retail_Territory__r.Zip_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/services/Credomatic_AccountServiceImp.cls
/*********************************************************************************
Class Name      : Credomatic_AccountServiceImp
Description     : Implementation of Account service methods
Created By      : Sebastian Torres
Created Date    : 2020-12-05
Modification Log:
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------------
Sebastian                 2021-03-29              Initial version

*********************************************************************************/
public class Credomatic_AccountServiceImp implements Credomatic_IAccountService {
    
    /*
     *  Create Account 
     */
    public void createAccount(String name) {
        fflib_ISObjectUnitOfWork uow = Credomatic_Application.unitOfWork.newInstance();

        createAccount(uow, name);

        uow.commitWork(); 
    }

    /*
     * createAccount 
     */
    public void createAccount(fflib_ISObjectUnitOfWork uow, String name) {
        Credomatic_AccountsSelector selector = (Credomatic_AccountsSelector) Credomatic_AccountsSelector.newInstance();
        List<Account> accList = selector.selectByName(name);
        
        
        if (accList.isEmpty()) {
            Account newAcc = new Account(Name = name);
            
            uow.registerNew(newAcc); 
        }
    }
    
    public void updateOwnerFromAssignment(List<Account> records) 
    {
        Set<Id> idToUpdateRelated = new Set<Id>();
        Set<String> zipCodes = new Set<String>();
        Map<String, Id> assignmentMap = new Map<String, Id>();
         //History Map
        Map<String, Id> historyAssignmentMap = new Map<String,Id>();
        
        //uow
        //fflib_ISObjectUnitOfWork uow = Credomatic_Application.unitOfWork.newInstance();
        
        //Implementation on how to get the correct Assignment based on Territory
        //First create the object, the fields, the selector, and think about the domain layer of that object
        for(Account acc : records) {
            zipCodes.add(acc.BillingPostalCode);
            idToUpdateRelated.add(acc.Id);
        }
        
        for(Retail_Territory__c t : Credomatic_RetailTerritoriesSelector.newInstance().selectByZip(zipCodes)) {
            territory_assignment__c assignment = Credomatic_TerritoriesUtilityClass.selectAssignedRep(t.territory_assignments__r);
            if(assignment != null) {
                assignmentMap.put(t.zip_code__c, assignment.User_Assigned__c);
                historyAssignmentMap.put(t.Zip_Code__c, t.Id);
            }
        }
        
          Credomatic_IAccounts accountDomain = (Credomatic_IAccounts)Credomatic_Application.Domain.newInstance(records);
		  accountDomain.updateAccOwner(assignmentMap);
        
        /*for(Account a : records) {
            a.OwnerId = assignmentMap.get(a.BillingPostalCode) != null? assignmentMap.get(a.BillingPostalCode) : a.OwnerId;
            idToUpdateRelated.add(a.Id);
        }*/
        //Missing the creation of the History object
        //CONSIDER Using the uow for creating the history object
        
        //Returning the Set to be passed to updateRelatedConsandOpps
    }
    
    public void updateRelatedConsandOpps(Set<Id> idSet) 
    {
        fflib_ISObjectUnitOfWork uow = Credomatic_Application.unitOfWork.newInstance();
        List<Account> accsWithRelated = Credomatic_AccountsSelector.newInstance().selectByIdWithConsAndOpps(idSet);
        
        //Credomatic_IOpportunities opportunities = (Credomatic_IOpportunities)Credomatic_Application.Domain.newInstance( recordList );
        //Credomatic_IContacts contacts = (Credomatic_IContacts)Credomatic_Application.Domain.newInstance( recordList );
                
        //Check on correct implementation or uow for the cons and opps updates
        for(Account acc : accsWithRelated) {
            
            if(acc.Opportunities.size() > 0) 
            {
                Credomatic_IOpportunities opportunities = (Credomatic_IOpportunities)Credomatic_Application.Domain.newInstance( acc.Opportunities );
				opportunities.updateOppOwner(uow, acc.OwnerId);                
            }
            
            if(!acc.IsPersonAccount && acc.Contacts.size() > 0) 
            {
                Credomatic_IContacts contacts = (Credomatic_IContacts)Credomatic_Application.Domain.newInstance( acc.Contacts );
				contacts.updateConOwner(uow, acc.OwnerId);  
            }
            
        }
        uow.commitWork();
    }

}