force-app/main/default/objects/Assignment_History__c/Assignment_History__c.object-meta.xml
<CustomObject>
    <label>Assignment History</label>
    <nameField>
        <displayFormat>AH-{0000}</displayFormat>
        <label>Assignment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assignment Histories</relationshipLabel>
    <relationshipName>Assignment_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assignment_History__c/fields/Changed_By__c.field-meta.xml
<CustomField>
    <fullName>Changed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Changed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_Histories2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment_History__c/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment_History__c/fields/New_Territory__c.field-meta.xml
<CustomField>
    <fullName>New_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Territory</label>
    <referenceTo>Retail_Territory__c</referenceTo>
    <relationshipLabel>Assignment Histories (New Territory)</relationshipLabel>
    <relationshipName>Assignment_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment_History__c/fields/Previous_Owner__c.field-meta.xml
<CustomField>
    <fullName>Previous_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment_History__c/fields/Previous_Territory__c.field-meta.xml
<CustomField>
    <fullName>Previous_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Territory</label>
    <referenceTo>Retail_Territory__c</referenceTo>
    <relationshipLabel>Assignment Histories</relationshipLabel>
    <relationshipName>Assignment_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Territory__c/Retail_Territory__c.object-meta.xml
<CustomObject>
    <description>This is the main object for Zip code territory tracking</description>
    <label>Retail Territory</label>
    <nameField>
        <label>Retail Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Territory__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <externalId>true</externalId>
    <label>Zip Code</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Territory_Assignment__c/Territory_Assignment__c.object-meta.xml
<CustomObject>
    <description>This is the main object to be able to assign the territory to a user.</description>
    <label>Territory Assignment</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Territory Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Assignment__c/fields/Retail_Territory__c.field-meta.xml
<CustomField>
    <fullName>Retail_Territory__c</fullName>
    <label>Retail Territory</label>
    <referenceTo>Retail_Territory__c</referenceTo>
    <relationshipLabel>Territory Assignments</relationshipLabel>
    <relationshipName>Territory_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Territory_Assignment__c/fields/User_Assigned__c.field-meta.xml
<CustomField>
    <fullName>User_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Assigned</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Assignment__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <formula>Retail_Territory__r.Zip_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/services/Credomatic_TerritoryAssignmentServiceImp.cls
/*********************************************************************************
Class Name      : Credomatic_TerritoryAssignmentServiceImp
Description     : 
Created By      : Sebastian Torres
Created Date    : 2021-04-05
Modification Log:
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------------
Sebastian                 2021-04-05              Initial version
*********************************************************************************/
public class Credomatic_TerritoryAssignmentServiceImp implements Credomatic_ITerritoryAssignmentService {
    
    public void updateOwnerFromAssignment(List<Account> records) 
    {
        Set<Id> idToUpdateRelated = new Set<Id>();
        Set<String> zipCodes = new Set<String>();
        Map<String, Id> assignmentMap = new Map<String, Id>();
         //History Map
        Map<String, Id> historyAssignmentMap = new Map<String,Id>();
        Credomatic_IAccounts accountDomain;
        
        
        
        //Implementation on how to get the correct Assignment based on Territory
        //First create the object, the fields, the selector, and think about the domain layer of that object
        for(Account acc : records) {
            zipCodes.add(acc.BillingPostalCode);
            idToUpdateRelated.add(acc.Id);
        }
        
        for(Retail_Territory__c t : Credomatic_RetailTerritoriesSelector.newInstance().selectByZip(zipCodes)) {
            territory_assignment__c assignment = Credomatic_TerritoriesUtilityClass.selectAssignedRep(t.territory_assignments__r);
            if(assignment != null) {
                assignmentMap.put(t.zip_code__c, assignment.User_Assigned__c);
                historyAssignmentMap.put(t.Zip_Code__c, t.Id);
            }
        }
        
        if(System.isBatch()) {
            //Here consider updating with the even functionality a Map<String, List<Id>> to validate
            List<Account> accsValidated = New List<Account>();
            for(Account a : records) {
                if(a.ownerId != historyAssignmentMap.get(a.BillingPostalCode)) accsValidated.add(a);
            }
            accountDomain = (Credomatic_IAccounts)Credomatic_Application.Domain.newInstance(accsValidated);
        } else{
          accountDomain = (Credomatic_IAccounts)Credomatic_Application.Domain.newInstance(records);
        }
        
         accountDomain.updateAccOwner(assignmentMap);
        
    }
    
    public void updateRelatedConsandOpps(Set<Id> idSet) 
    {
        fflib_ISObjectUnitOfWork uow = Credomatic_Application.unitOfWork.newInstance();
        List<Account> accsWithRelated = Credomatic_AccountsSelector.newInstance().selectByIdWithConsAndOpps(idSet);
        
        //Credomatic_IOpportunities opportunities = (Credomatic_IOpportunities)Credomatic_Application.Domain.newInstance( recordList );
        //Credomatic_IContacts contacts = (Credomatic_IContacts)Credomatic_Application.Domain.newInstance( recordList );
                
        //Check on correct implementation or uow for the cons and opps updates
        for(Account acc : accsWithRelated) {
            
            if(acc.Opportunities.size() > 0) 
            {
                Credomatic_DiagnosticsInstrumentation.debug('Account ' + acc.name + 'Has ' + acc.Opportunities.size() + ' Opps to update');
                Credomatic_IOpportunities opportunities = (Credomatic_IOpportunities)Credomatic_Application.Domain.newInstance( acc.Opportunities );
				opportunities.updateOppOwner(uow, acc.OwnerId);                
            }
            
            if(!acc.IsPersonAccount && acc.Contacts.size() > 0) 
            {
                Credomatic_DiagnosticsInstrumentation.debug('Account ' + acc.name + 'Has ' + acc.Contacts.size() + ' Contacts to update');
                Credomatic_IContacts contacts = (Credomatic_IContacts)Credomatic_Application.Domain.newInstance( acc.Contacts );
				contacts.updateConOwner(uow, acc.OwnerId);  
            }
            
        }
        uow.commitWork();
    }

    public void createAssignmentHistory(List<Account> accList, Map<Id, Account> previousRecords) {
        fflib_ISObjectUnitOfWork uow = Credomatic_Application.unitOfWork.newInstance();
        
        Map<String, Id> assignmentMap = new Map<String, Id>();
        Set<String> zipCodes = new Set<String>();
         //History Map
        Map<String, Id> historyAssignmentMap = new Map<String,Id>();
        
        for(Account acc : accList) {
            zipCodes.add(acc.BillingPostalCode);
            zipCodes.add(previousRecords.get(acc.Id).BillingPostalCode);
        }
        
        for(Retail_Territory__c t : Credomatic_RetailTerritoriesSelector.newInstance().selectByZip(zipCodes)) {
            territory_assignment__c assignment = Credomatic_TerritoriesUtilityClass.selectAssignedRep(t.territory_assignments__r);
            if(assignment != null) {
                assignmentMap.put(t.zip_code__c, assignment.User_Assigned__c);
                historyAssignmentMap.put(t.Zip_Code__c, t.Id);
            }
        }
        
        for(Account a : accList) {
            Assignment_History__c aHistory = new Assignment_History__c();
            aHistory.Previous_Owner__c = previousRecords.get(a.id).ownerId;
            aHistory.New_Owner__c = a.ownerId;
            aHistory.Previous_Territory__c = historyAssignmentMap.get(previousRecords.get(a.id).BillingPostalCode);
            aHistory.New_Territory__c = historyAssignmentMap.get(a.BillingPostalCode);
            aHistory.Changed_By__c = a.LastModifiedById;
            uow.registerNew(aHistory, Assignment_History__c.account__c, a);
        }
        
        uow.commitWork();
        
    }
    
    public void updateOwnersFromAssignmentChange(List<Territory_Assignment__c> tAssignments, Map<Id, Territory_Assignment__c> previousRecords) 
    {
        Set<String> setZipCode = new Set<String>();
        Map<Id, Id> assignmentMap = new Map<Id, Id>();
        for(Territory_Assignment__c ta : tAssignments) {
            assignmentMap.put(previousRecords.get(ta.Id).User_Assigned__c, ta.User_Assigned__c);
            setZipCode.add(ta.Zip_Code__c);
        }
        
        List<Account> accs = Credomatic_AccountsSelector.newInstance().selectByOwnerandZipCode(assignmentMap.keySet(), setZipCode);
        fflib_ISObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new Schema.SObjectType[] { Account.SObjectType });
        Credomatic_IAccounts accounts = (Credomatic_IAccounts)Credomatic_Application.Domain.newInstance(accs);
        accounts.updateAccsOwnerFromTerritory(uow, assignmentMap);
        
        uow.commitWork();
        
    }

}